os      : linux
language: c
dist    : bionic
env     :
  global:
  - TOOLS_DIR: ~/tools
  - VERILATOR_ROOT: ~/tools/verilator
  - YOSYS_ROOT: ~/tools/yosys
  - RISCV: ~/tools/riscv64-unknown-elf
before_install :
- sudo apt-get --yes install flex bison libfl2 libfl-dev perl build-essential clang bison flex libreadline-dev gawk tcl-dev libffi-dev graphviz xdot pkg-config python3 libboost-system-dev libboost-python-dev libboost-filesystem-dev zlib1g-dev
jobs:
  include:
  - name: "Confidence Checks - Core"
    script:
    - source ./bin/install-verilator.sh
    - source ./bin/install-toolchain.sh
    - source ./bin/conf.sh
    - make -B build-core_top
    - make run-unit-core-example
    - make run-unit-core-branch-tgt-trap
    - make run-unit-core-imem-access-trap
    - make run-unit-core-mul
    - make run-unit-core-div
  - name: "Confidence Checks - CCX"
    script:
    - source ./bin/install-verilator.sh
    - source ./bin/install-toolchain.sh
    - source ./bin/conf.sh
    - make -B build-ccx_top
    - make -B build-unit-tests-ccx
    - make -B run-unit-tests-ccx
  - name: "Arch Tests - I"
    script:
    - source ./bin/install-verilator.sh
    - source ./bin/install-toolchain.sh
    - source ./bin/conf.sh
    - make -B build-ccx_top
    - make arch-test-verify-uc64-I
  - name: "Arch Tests - M"
    script:
    - source ./bin/install-verilator.sh
    - source ./bin/install-toolchain.sh
    - source ./bin/conf.sh
    - make -B build-ccx_top
    - make arch-test-verify-uc64-M
  - name: "Arch Tests - C"
    script:
    - source ./bin/install-verilator.sh
    - source ./bin/install-toolchain.sh
    - source ./bin/conf.sh
    - make -B build-ccx_top
    - make arch-test-verify-uc64-C
  - name: "Designer Assertions"
    script:
    - source ./bin/install-yosys.sh
    - source ./bin/install-symbiyosys.sh
    - source ./bin/install-boolector.sh
    - source ./bin/conf.sh
    - make -j $(nproc) da-prove-all
  - name: "riscv-formal"
    script:
    - source ./bin/install-yosys.sh
    - source ./bin/install-symbiyosys.sh
    - source ./bin/install-boolector.sh
    - source ./bin/conf.sh
    - make riscv-formal-clean riscv-formal-prepare
    - export PATH=$YOSYS_ROOT:$PATH
    - make -C work/core/riscv-formal insn_add_ch0
    - make -C work/core/riscv-formal insn_beq_ch0
    - make -C work/core/riscv-formal insn_ld_ch0
    - make -C work/core/riscv-formal insn_sd_ch0
  - name: "Synthesis - Core"
    script:
    - source ./bin/install-yosys.sh
    - source ./bin/conf.sh
    - make synthesise-cmos
  - name: "Benchmarks - Embench IoT"
    script:
    - source ./bin/install-verilator.sh
    - source ./bin/install-toolchain.sh
    - source ./bin/conf.sh
    - make build-ccx_top
    - make build-embench-binaries
    - make build-embench-targets
    - make -j 2 run-embench-targets
    - grep -rn ">> Finished after .* clock cycles" work/embench/src/ | sort
cache   :
  directories:
  - ~/tools/verilator
  - ~/tools/yosys
  - ~/tools/symbiyosys
  - ~/tools/boolector
  - ~/tools/riscv64-unknown-elf

